# Generated by Django 5.1.5 on 2025-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licence_img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('company', 'Client Company'), ('client', 'Client')], max_length=20),
        ),
    ]
