# Generated by Django 5.1.5 on 2025-02-11 07:57

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_driver_driving_license_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefFleet',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverChiefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.chieffleet')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.driver')),
            ],
        ),
        migrations.AddField(
            model_name='chieffleet',
            name='drivers',
            field=models.ManyToManyField(related_name='chief_fleets', through='users.DriverChiefRequest', to='users.driver'),
        ),
    ]
