# Generated by Django 5.1.5 on 2025-02-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_chieffleet_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='chief_fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.chieffleet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('company', 'Client Company'), ('client', 'Client'), ('chief', 'Chief Fleet')], max_length=20),
        ),
    ]
