# Generated by Django 5.1.5 on 2025-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_driver_chief_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_admin_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
