# Generated by Django 5.1.5 on 2025-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
