# Generated by Django 5.1.5 on 2025-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_alter_truck_mileage_alter_truck_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='max_load_capacity',
            field=models.FloatField(help_text='Maximum capacity in tonnes'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional specifications', null=True),
        ),
    ]
