# Generated by Django 5.1.5 on 2025-02-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_admin_last_admin_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('cargo_type', models.CharField(choices=[('container', 'Container'), ('pallets_boxes', 'Pallets and Boxes'), ('bulk_fret', 'Bulk Fret (Liquid, Sand, Food Products)'), ('vehicle', 'Vehicle'), ('animals', 'Animals'), ('furniture_tools', 'Furniture or Tools'), ('other', 'Other')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('dimensions', models.CharField(help_text='Dimensions in LxWxH format (e.g., 100x50x30 cm)', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items or quantity')),
                ('pickup_location', models.CharField(max_length=100)),
                ('pickup_date_time', models.DateTimeField()),
                ('delivery_location', models.CharField(max_length=100)),
                ('delivery_date_time', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True, help_text='e.g., perishable goods, fragile items', null=True)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='sending_requests')),
                ('special_conditions', models.TextField(blank=True, help_text='e.g., refrigeration required, special handling', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=20, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_requests', to='users.member')),
            ],
            options={
                'verbose_name': 'Sending Request',
                'verbose_name_plural': 'Sending Requests',
            },
        ),
    ]
