# Generated by Django 5.1.5 on 2025-02-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendingRequest', '0002_alter_sendingrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingrequest',
            name='priority',
            field=models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='sendingrequestfleetassignment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('assigned', 'Assigned')], default='assigned', max_length=20),
        ),
    ]
