# Generated by Django 5.1.5 on 2025-03-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendingRequest', '0003_alter_sendingrequest_priority_and_more'),
        ('truck', '0003_alter_truck_max_load_capacity_alter_truck_notes'),
        ('users', '0010_alter_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingrequest',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='sendingrequest',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the transport service', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='sendingrequest',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate as a percentage (e.g., 5.00 for 5%)', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='sendingrequest',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price including commission', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='sendingrequestfleetassignment',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Truck', to='truck.truck'),
        ),
        migrations.AlterField(
            model_name='sendingrequestfleetassignment',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Driver', to='users.driver'),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('cargo_type', models.CharField(choices=[('container', 'Container'), ('pallets_boxes', 'Pallets and Boxes'), ('bulk_fret', 'Bulk Fret (Liquid, Sand, Food Products)'), ('vehicle', 'Vehicle'), ('animals', 'Animals'), ('furniture_tools', 'Furniture or Tools'), ('other', 'Other')], max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('dimensions', models.CharField(help_text='Dimensions in LxWxH format (e.g., 100x50x30 cm)', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items or quantity')),
                ('pickup_location', models.CharField(max_length=100)),
                ('pickup_date_time', models.DateTimeField()),
                ('delivery_location', models.CharField(max_length=100)),
                ('delivery_date_time', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True, help_text='e.g., perishable goods, fragile items', null=True)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='sending_requests')),
                ('special_conditions', models.TextField(blank=True, help_text='e.g., refrigeration required, special handling', null=True)),
                ('priority', models.CharField(choices=[('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_note', to='users.member')),
            ],
            options={
                'verbose_name': 'Sending Request',
                'verbose_name_plural': 'Sending Requests',
            },
        ),
        migrations.AddField(
            model_name='sendingrequestfleetassignment',
            name='delivery_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_assignments', to='sendingRequest.deliverynote'),
        ),
    ]
