# Generated by Django 5.1.5 on 2025-02-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='duration_days',
            new_name='duration_month',
        ),
    ]
